[versions]
agp = "8.13.1"
kotlin = "2.2.21"
appcompat = "1.7.1"
coreKtx = "1.17.0"
constraintlayout = "2.2.1"
recyclerview = "1.4.0"
cardview = "1.0.0"
lifecycle = "2.9.4"
retrofit = "2.11.0"
okhttp3 = "4.12.0"
gson = "2.12.1"
glide = "4.16.0"
junit = "4.13.2"
mockito = "5.17.0"
runner = "1.7.0"
espresso = "3.7.0"
archCore = "2.2.0"

[libraries]
# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

# AndroidX Core
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }

# Lifecycle
lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle" }

# Networking
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }

# JSON
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# Image Loading
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "archCore" }
test-runner = { module = "androidx.test:runner", version.ref = "runner" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }